### ISSUE TITLE
Implement `checkEnv` built-in command

### ISSUE THREAD

**Issue by fsommar** [fsommar/smsh#5]
If no arguments are given to `checkEnv` then `printenv | sort | pager` should be executed.

If arguments are being given then `printenv | grep <arguments> | sort | pager` should be executed.

The `pager` program should be first and foremost selected based on the `PAGER` environment variable. If that doesn't exist then `less` should be chosen and if all fails then `more`.

**Comment by Millevik** [comment]
Closed in f58a724770e17001a24a3229f29769044303dbab.
